fix: macOS build

diff --git a/Scripts/build_rust_dependencies b/Scripts/build_rust_dependencies
--- a/Scripts/build_rust_dependencies
+++ b/Scripts/build_rust_dependencies
@@ -15,9 +15,9 @@ PACT_FOUNDATION_REPO="https://github.com/pact-foundation/pact-reference.git"
 
 if [ ! -d "$PWD/$PRODUCT_NAME.xcodeproj" ]
 then
-	echo "🚨 Run this from the same folder where your '$PRODUCT_NAME.xcodeproj' lives."
-	echo "⚠️  You are runing it in $PWD"
-	exit 1
+    echo "🚨 Run this from the same folder where your '$PRODUCT_NAME.xcodeproj' lives."
+    echo "⚠️  You are runing it in $PWD"
+    exit 1
 fi
 
 #######################
@@ -27,20 +27,20 @@ fi
 echo "👮‍♀️  Verifying project and dependencies' folder setup..."
 
 if [[ "$CI" == true ]]; then
-	echo "ℹ️ Adding submodule ${PACT_FOUNDATION_REPO}"
-	if [ ! -d "$PWD/pact-reference"]; then
-		git submodule add $PACT_FOUNDATION_REPO
-	fi
-	git submodule update --init
-	cd pact-reference/rust/pact_ffi
+    echo "ℹ️ Adding submodule ${PACT_FOUNDATION_REPO}"
+    if [ ! -d "$PWD/pact-reference" ]; then
+        git submodule add $PACT_FOUNDATION_REPO
+    fi
+    git submodule update --init
+    cd pact-reference/rust/pact_ffi
 elif [ ! -d "$PWD/../pact-reference" ]; then
-	echo "🚨 Missing pact-foundation/pact-reference repo."
-	echo "⚠️  Make sure you 'git clone ${PACT_FOUNDATION_REPO}' at the same folder level as your $PRODUCT_NAME."
-	exit 1
+    echo "🚨 Missing pact-foundation/pact-reference repo."
+    echo "⚠️  Make sure you 'git clone ${PACT_FOUNDATION_REPO}' at the same folder level as your $PRODUCT_NAME."
+    exit 1
 else
-	echo "👍  Project setup seems to be in order."
-	echo "ℹ️  Changing location to ${LIBPACT_FFI_DIR}"
-	cd $LIBPACT_FFI_DIR
+    echo "👍  Project setup seems to be in order."
+    echo "ℹ️  Changing location to ${LIBPACT_FFI_DIR}"
+    cd "$LIBPACT_FFI_DIR"
 fi
 
 #######################
@@ -51,13 +51,13 @@ fi
 
 echo "👮‍♀️  Checking if Rust is installed..."
 if which cargo >/dev/null; then
-	echo "👍  cargo installed"
+    echo "👍  cargo installed"
 elif command -v ~/.cargo/bin/cargo &> /dev/null; then
-	echo "👍  cargo installed in ~/.cargo/bin/"
+    echo "👍  cargo installed in ~/.cargo/bin/"
 else
-	echo "🚨  Rust/Cargo not installed"
-	echo "ERROR: cargo is required and is was found on this machine. See https://www.rust-lang.org/tools/install"
- 	exit 1
+    echo "🚨  Rust/Cargo not installed"
+    echo "ERROR: cargo is required and is was found on this machine. See https://www.rust-lang.org/tools/install"
+     exit 1
 fi
 
 ##############################################
@@ -71,9 +71,9 @@ echo "✅  libpact_ffi built"
 
 echo "ℹ️  Setting LD_LIBRARY_PATH to include $LIBPACT_PRODUCT_DIR"
 if [[ "$CI" == true ]]; then
-	export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${WORKSPACE}/pact-reference/rust/target/debug"
+    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${WORKSPACE}/pact-reference/rust/target/debug"
 else
-	export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${LIBPACT_PRODUCT_DIR}"
+    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${LIBPACT_PRODUCT_DIR}"
 fi
 
 #######################
@@ -81,7 +81,7 @@ fi
 #######################
 
 echo "ℹ️  Changing directory back to ${WORKSPACE}"
-cd ${WORKSPACE}
+cd "${WORKSPACE}"
 
 ##############################################################################################################
 # Run Swift buld and test                                                                                    #
@@ -89,13 +89,13 @@ cd ${WORKSPACE}
 ##############################################################################################################
 
 echo "ℹ️  Running swift build:"
-swift build -Xlinker -L$LIBPACT_PRODUCT_DIR
+swift build -Xlinker -L"$LIBPACT_PRODUCT_DIR"
 
 echo "ℹ️  Running swift test with -Xlinker -L$LIBPACT_PRODUCT_DIR"
 
 if [[ "$CI" == true ]]; then
-	BIN_PATH="${WORKSPACE}/pact-reference/rust/target/debug"
-	swift test -Xlinker -L$BIN_PATH
+    BIN_PATH="${WORKSPACE}/pact-reference/rust/target/debug"
+    swift test -Xlinker -L"$BIN_PATH"
 else
-	swift test -Xlinker -L$LIBPACT_PRODUCT_DIR
+    swift test -Xlinker -L"$LIBPACT_PRODUCT_DIR"
 fi
diff --git a/Scripts/build_test_linux b/Scripts/build_test_linux
--- a/Scripts/build_test_linux
+++ b/Scripts/build_test_linux
@@ -34,9 +34,9 @@ PACT_FOUNDATION_REPO="https://github.com/pact-foundation/pact-reference.git"
 
 if [ ! -d "$PWD/$PRODUCT_NAME.xcodeproj" ]
 then
-	echo "🚨 Run this from the same folder where your '$PRODUCT_NAME.xcodeproj' lives."
-	echo "⚠️  You are runing it in $PWD"
-	exit 1
+    echo "🚨 Run this from the same folder where your '$PRODUCT_NAME.xcodeproj' lives."
+    echo "⚠️  You are runing it in $PWD"
+    exit 1
 fi
 
 #######################
@@ -46,30 +46,30 @@ fi
 echo "👮‍♀️  Verifying project and dependencies' folder setup..."
 
 if [[ "$CI" == true ]]; then
-	echo "ℹ️ Adding submodule ${PACT_FOUNDATION_REPO}"
-	if [ ! -d "$PWD/pact-reference" ]; then
-		git submodule add $PACT_FOUNDATION_REPO
-		git submodule update --init
+    echo "ℹ️ Adding submodule ${PACT_FOUNDATION_REPO}"
+    if [ ! -d "$PWD/pact-reference" ]; then
+        git submodule add $PACT_FOUNDATION_REPO
+        git submodule update --init
 
-		echo "ℹ️  Changing location to ${LIBPACT_FFI_DIR}"
-		cd $LIBPACT_FFI_DIR
-		git fetch --all --tags
-		git checkout tags/libpact_ffi-v0.3.11
-	fi
+        echo "ℹ️  Changing location to ${LIBPACT_FFI_DIR}"
+        cd "$LIBPACT_FFI_DIR"
+        git fetch --all --tags
+        git checkout tags/libpact_ffi-v0.3.11
+    fi
 
-	export LD_LIBRARY_PATH="/usr/local/lib"
+    export LD_LIBRARY_PATH="/usr/local/lib"
 
 elif [ ! -d "$PWD/../pact-reference" ]; then
-	# TODO: fix this for running locally
-	echo "🚨 Missing pact-foundation/pact-reference repo."
-	echo "⚠️  Make sure you 'git clone ${PACT_FOUNDATION_REPO}' at the same folder level as your $PRODUCT_NAME."
-	exit 1
+    # TODO: fix this for running locally
+    echo "🚨 Missing pact-foundation/pact-reference repo."
+    echo "⚠️  Make sure you 'git clone ${PACT_FOUNDATION_REPO}' at the same folder level as your $PRODUCT_NAME."
+    exit 1
 else
-	echo "👍  Project setup seems to be in order."
+    echo "👍  Project setup seems to be in order."
 fi
 
 echo "ℹ️  Changing location to ${LIBPACT_FFI_DIR}"
-cd $LIBPACT_FFI_DIR
+cd "$LIBPACT_FFI_DIR"
 
 #######################
 # Setup               #
@@ -79,13 +79,13 @@ cd $LIBPACT_FFI_DIR
 
 echo "👮‍♀️  Checking if Rust is installed..."
 if which cargo >/dev/null; then
-	echo "👍  cargo installed"
+    echo "👍  cargo installed"
 elif command -v ~/.cargo/bin/cargo &> /dev/null; then
-	echo "👍  cargo installed in ~/.cargo/bin/"
+    echo "👍  cargo installed in ~/.cargo/bin/"
 else
-	echo "🚨  Rust/Cargo not installed"
-	echo "ERROR: cargo is required and is was found on this machine. See https://www.rust-lang.org/tools/install"
- 	exit 1
+    echo "🚨  Rust/Cargo not installed"
+    echo "ERROR: cargo is required and is was found on this machine. See https://www.rust-lang.org/tools/install"
+     exit 1
 fi
 
 ##############################################
@@ -105,7 +105,7 @@ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LIBPACT_PRODUCT_DIR
 #######################
 
 echo "ℹ️  Changing directory back to ${WORKSPACE}"
-cd ${WORKSPACE}
+cd "${WORKSPACE}"
 
 ##############################################################################################################
 # Run Swift buld and test                                                                                    #
@@ -113,7 +113,7 @@ cd ${WORKSPACE}
 ##############################################################################################################
 
 echo "ℹ️  Running swift build:"
-swift build -Xlinker -L$LIBPACT_PRODUCT_DIR
+swift build -Xlinker -L"$LIBPACT_PRODUCT_DIR"
 
 echo "ℹ️  Running swift test with -Xlinker -L$LIBPACT_PRODUCT_DIR"
-swift test -Xlinker -L$LIBPACT_PRODUCT_DIR
+swift test -Xlinker -L"$LIBPACT_PRODUCT_DIR"
diff --git a/Scripts/release b/Scripts/release
--- a/Scripts/release
+++ b/Scripts/release
@@ -26,30 +26,30 @@ set -o pipefail
 ####################
 
 function help {
-	echo "Usage: release VERSION RELEASE_NAME [DRY_RUN]"
-	echo
-	echo "VERSION should be the version to release and should not include the 'v' prefix"
-	echo "RELEASE_NAME should be the type of release 'Bugfix Release / Maintenance Release'"
-	echo
-	echo "FLAGS"
-	echo "  -d  Dry run, won't push anything"
-	echo
-	echo "  Example: ./Scripts/release 1.0.0 'Bugfix Release' -d"
-	echo
-	exit 2
+    echo "Usage: release VERSION RELEASE_NAME [DRY_RUN]"
+    echo
+    echo "VERSION should be the version to release and should not include the 'v' prefix"
+    echo "RELEASE_NAME should be the type of release 'Bugfix Release / Maintenance Release'"
+    echo
+    echo "FLAGS"
+    echo "  -d  Dry run, won't push anything"
+    echo
+    echo "  Example: ./Scripts/release 1.0.0 'Bugfix Release' -d"
+    echo
+    exit 2
 }
 
 function die {
-	echo "🚨  [ERROR] $@"
-	echo
-	exit 1
+    echo "🚨  [ERROR] $@"
+    echo
+    exit 1
 }
 
 function handleInput {
-	if [[ ! $1 =~ ^[Yy]$ ]]; then
-		echo "⚠️  Release aborted!"
-		exit 1
-	fi
+    if [[ ! $1 =~ ^[Yy]$ ]]; then
+        echo "⚠️  Release aborted!"
+        exit 1
+    fi
 }
 
 #####################
@@ -65,10 +65,10 @@ fi
 ##############################
 
 if [[ "$CI" == true ]] ; then
-	die "🚨  Running on CI is not supported! Requires user input while running the release script."
+    die "🚨  Running on CI is not supported! Requires user input while running the release script."
 else
-	echo "👮‍♀️  Running on local machine: 👍"
-	SCRIPTS_DIR="${BASH_SOURCE[0]%/*}"
+    echo "👮‍♀️  Running on local machine: 👍"
+    SCRIPTS_DIR="${BASH_SOURCE[0]%/*}"
 fi
 
 ##############################
@@ -76,31 +76,31 @@ fi
 ##############################
 
 # Get the latest release tag
-LATEST_TAG=`git describe --match "v[0-9].*" --abbrev=0 HEAD`
+LATEST_TAG="$(git describe --match "v[0-9].*" --abbrev=0 HEAD)"
 
 echo "ℹ️  The last release tag number is: ${LATEST_TAG}"
 
 read -r -p "Did you provide the correctly incremented number for the new release tag? [Y/n] " -n 1 USER_INPUT
 echo
-handleInput $USER_INPUT
+handleInput "$USER_INPUT"
 echo
 
 read -r -p "Have you updated all the documentation files? [Y/n] " -n 1 USER_INPUT
 echo
-handleInput $USER_INPUT
+handleInput "$USER_INPUT"
 echo
 
 echo "ℹ️  The following commits will be recorded with the tag:"
-git log --pretty='* %h - %s (%an)' ${LATEST_TAG}..HEAD
+git log --pretty='* %h - %s (%an)' "${LATEST_TAG}"..HEAD
 echo
 
 read -r -p "Have you prepared a draft release on GitHub.com? [Y/n] " -n 1 USER_INPUT
 echo
-handleInput $USER_INPUT
+handleInput "$USER_INPUT"
 
 read -r -p "You named the release name with something meaningful like \"Bugfix\" or \"Feature \". Right? [Y/n] " -n 1 USER_INPUT
 echo
-handleInput $USER_INPUT
+handleInput "$USER_INPUT"
 
 ####################
 # Variables        #
@@ -120,29 +120,29 @@ VERSION_TAG="v$VERSION"
 ####################
 
 function updateVersionFile {
-	sed -i '' "2s/.*/let pactSwiftVersion = \"$@\"/" $VERSION_FILE
+    sed -i '' "2s/.*/let pactSwiftVersion = \"$@\"/" "$VERSION_FILE"
 
-	MARKETING_VERSION="MARKETING_VERSION = $@"
-	sed -i '' "2s/.*/$MARKETING_VERSION/" $CONFIGURATION_FILE
+    MARKETING_VERSION="MARKETING_VERSION = $@"
+    sed -i '' "2s/.*/$MARKETING_VERSION/" "$CONFIGURATION_FILE"
 }
 
 function pushNewVersion {
-	updateVersionFile "$VERSION"
+    updateVersionFile "$VERSION"
 
-	echo ${RELEASE_NAME} > TAG_MESSAGE_FILE.md
-	git log --pretty='* %h - %s (%an)' ${LATEST_TAG}..HEAD >> TAG_MESSAGE_FILE.md
+    echo "${RELEASE_NAME}" > TAG_MESSAGE_FILE.md
+    git log --pretty='* %h - %s (%an)' "${LATEST_TAG}"..HEAD >> TAG_MESSAGE_FILE.md
 
-	git add $VERSION_FILE
-	git add $CONFIGURATION_FILE
-	git add $RELEASE_NOTES
+    git add "$VERSION_FILE"
+    git add "$CONFIGURATION_FILE"
+    git add "$RELEASE_NOTES"
 
-	git commit -m "${RELEASE_NAME}"
+    git commit -m "${RELEASE_NAME}"
 
-	echo "🏷  Tagging the current commit"
-	git tag "$VERSION_TAG" -F TAG_MESSAGE_FILE.md || die "Failed to tag version"
+    echo "🏷  Tagging the current commit"
+    git tag "$VERSION_TAG" -F TAG_MESSAGE_FILE.md || die "Failed to tag version"
 
-	echo "🚀  Tagging the current commit"
-	git push --atomic origin main $VERSION_TAG || die "Failed to push the release commit with tag '$VERSION_TAG' to origin"
+    echo "🚀  Tagging the current commit"
+    git push --atomic origin main "$VERSION_TAG" || die "Failed to push the release commit with tag '$VERSION_TAG' to origin"
 
 }
 
@@ -152,12 +152,12 @@ function pushNewVersion {
 
 echo "👮‍♀️  Verifying if version tag is reasonable..."
 
-echo $VERSION_TAG | grep -q "^vv"
+echo "$VERSION_TAG" | grep -q "^vv"
 if [ $? -eq 0 ]; then
     die "This tag ($VERSION) is in an incorrect format. You should remove the 'v' prefix."
 fi
 
-echo $VERSION_TAG | grep -q -E "^v[0-9]+\.[0-9]+\.[0-9]+(-\w+(\.\d)?)?$"
+echo "$VERSION_TAG" | grep -q -E "^v[0-9]+\.[0-9]+\.[0-9]+(-\w+(\.\d)?)?$"
 if [ $? -ne 0 ]; then
     die "This tag $VERSION is in an incorrect format. It should be in 'v{MAJOR}.{MINOR}.{PATCH}(-{PRERELEASE_NAME}.{PRERELEASE_VERSION})' form."
 fi
@@ -172,19 +172,19 @@ fi
 
 echo "🏗  Generating release notes into $RELEASE_NOTES"
 # backup the existing CHANGELOG.md to CHANGELOG.backup
-cp $RELEASE_NOTES ${RELEASE_NOTES}.backup
+cp "$RELEASE_NOTES" "${RELEASE_NOTES}.backup"
 
 # Prepare the title for this release
-echo "# ${VERSION} - ${RELEASE_NAME}" > ${RELEASE_NOTES}.next
+echo "# ${VERSION} - ${RELEASE_NAME}" > "${RELEASE_NOTES}.next"
 
 # Get the commits from last change
-git log --pretty='* %h - %s (%an)' ${LATEST_TAG}..HEAD >> ${RELEASE_NOTES}.next
+git log --pretty='* %h - %s (%an)' "${LATEST_TAG}"..HEAD >> "${RELEASE_NOTES}.next"
 
 # Stage the updated CHANGELOG.md
-git add $RELEASE_NOTES || { die "Failed to add ${RELEASE_NOTES} to INDEX"; }
+git add "$RELEASE_NOTES" || { die "Failed to add ${RELEASE_NOTES} to INDEX"; }
 
 # Read the notes for this release and append them to the old CHANGELOG.md
-cat $RELEASE_NOTES.next | cat - ${RELEASE_NOTES}.backup > ${RELEASE_NOTES}
+cat "$RELEASE_NOTES.next" | cat - "${RELEASE_NOTES}.backup" > "${RELEASE_NOTES}"
 
 echo "🚢  Releasing version $VERSION (tag: $VERSION_TAG)..."
 
@@ -195,27 +195,27 @@ git diff --quiet HEAD "origin/$REMOTE_BRANCH" || die "HEAD is not aligned to ori
 echo "🏷  Tagging release version..."
 
 if [ -z "$DRY_RUN" ]; then
-	echo "🚅  Pushing release version tag to origin..."
+    echo "🚅  Pushing release version tag to origin..."
 
-	pushNewVersion
+    pushNewVersion
 
-	echo
-	echo "--------  🎉  Created a new PactSwift version tag  🎉 --------------------------------"
-	echo "--------  🏷   Version:	$VERSION_TAG"
-	echo "--------  ✏️   Name: 	$RELEASE_NAME"
-	echo "--------"
-	echo "--------  🚀  Go and link you draft release for '$VERSION_TAG' with this tagged commit."
-	echo "--------  🔗  https://github.com/surpher/PactSwift/releases"
-	echo
+    echo
+    echo "--------  🎉  Created a new PactSwift version tag  🎉 --------------------------------"
+    echo "--------  🏷   Version:    $VERSION_TAG"
+    echo "--------  ✏️   Name:     $RELEASE_NAME"
+    echo "--------"
+    echo "--------  🚀  Go and link you draft release for '$VERSION_TAG' with this tagged commit."
+    echo "--------  🔗  https://github.com/surpher/PactSwift/releases"
+    echo
 
 else
-	echo "-> Dry run completed."
+    echo "-> Dry run completed."
 fi
 
 ####################
 # Cleanup          #
 ####################
 
-rm ${RELEASE_NOTES}.next
-rm ${RELEASE_NOTES}.backup
+rm "${RELEASE_NOTES}.next"
+rm "${RELEASE_NOTES}.backup"
 rm TAG_MESSAGE_FILE.md
