chore: Update release script

diff --git a/Scripts/release b/Scripts/release
--- a/Scripts/release
+++ b/Scripts/release
@@ -62,6 +62,7 @@ function pushNewVersion {
 	git add $RELEASE_NOTES
 
 	git commit -m "${RELEASE_NAME}"
+	git tag -a $VERSION_TAG -m "Release version $VERSION_TAG" || die "Failed to tag version"
 
 	git push origin || die "Failed to push version changes to origin"
 	git push origin "$VERSION_TAG" || die "Failed to push tag '$VERSION_TAG' to origin"
@@ -106,7 +107,6 @@ git fetch origin || die "Failed to fetch origin"
 git diff --quiet HEAD "origin/$REMOTE_BRANCH" || die "HEAD is not aligned to origin/$REMOTE_BRANCH. Cannot update version safely"
 
 echo "🏷  Tagging release version"
-git tag "$VERSION_TAG" -F "$RELEASE_NOTES" || die "Failed to tag version"
 
 if [ -z "$DRY_RUN" ]; then
 	echo "🚅  Pushing release version tag to origin"
@@ -119,6 +119,5 @@ if [ -z "$DRY_RUN" ]; then
 
 	rm ${RELEASE_NOTES}.backup
 else
-	git tag -d "$VERSION_TAG"
 	echo "-> Dry run completed."
 fi
