chore(Carthage) Remove 3rd party depencency
Removing Nimble as a dependency.

diff --git a/.github/workflows/test_xcode-default.yml b/.github/workflows/test_xcode-default.yml
--- a/.github/workflows/test_xcode-default.yml
+++ b/.github/workflows/test_xcode-default.yml
@@ -20,11 +20,10 @@ jobs:
           git lfs install --skip-smudge
           brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
           brew install swiftlint xcbeautify
-          carthage update --platform ios,macos --no-use-binaries
-      - name: Build and Test SPM
+      - name: Build and Test SPM support
         run: |
           set -o pipefail && swift build -c debug
-          echo "SKIPPING: \"set -o pipefail && swift test -Xlinker -LResources/macOS | xcbeautify\""
+          echo "⚠️ SKIPPING: \"set -o pipefail && swift test -Xlinker -LResources/macOS | xcbeautify\""
       - name: Test iOS target
         run: |
           set -o pipefail && xcodebuild clean test -project PactSwift.xcodeproj -scheme PactSwift-iOS -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcbeautify
@@ -34,6 +33,6 @@ jobs:
       - name: Test it builds for Carthage
         run: |
           carthage build --no-skip-current
-      - name: Trigger tests on examples repos
+      - name: Trigger tests on examples repo
         run: |
           curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/surpher/pact-swift-examples/dispatches --data '{"event_type": "build_application"}'
